version: "1.0"
projectName: NL_MIHE_GLProcessingProject
runtimes:
- runtimeAlias: NL_JL_EDGE2
  assets:
  - name: fld_113520462_stage00.projects.flf138fac18710452b89211b77f6c671f9.integrations:processTransactionRecord
    type: flow
    stepId: /4
    reference: fld_113520462_stage00.projects.flf138fac18710452b89211b77f6c671f9.WmPackageServiceProvider.project.nl_mihe_glprocessing.integrations:VerifyInvoiceInERP
  - name: ProcessTransactionRecord
    type: workflow
    uid: fld06b3d2ed8d0430c88733418c9a1ce9c
    stepId: a1
    reference: project.nl_mihe_glprocessing.integrations:VerifyInvoiceInERP
